apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: liturbe
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: registry.dev.afsmtddso.com/liturbe-harbor-project/app@sha256:0a947937c3e4e934d78cc11be871cee1a54282e307550a2e7cd0931317083648
        ports:
        - containerPort: 5000
