apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: liturbe
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: registry.dev.afsmtddso.com/liturbe-harbor-project/db@sha256:8dacca5276288e3b8ff2d9b8ce7b49737181e5d0ed91b023c708817fa4750012
        ports:
        - containerPort: 5432
